import { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Box, Button, Checkbox, Chip, Container, FormControl, FormControlLabel, InputLabel, Link, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, ToggleButton, ToggleButtonGroup, Typography } from '@mui/material';
import { pseudonymize, applySchema, buildPrompt, parseSessionResponse, validateResults, projectOutput, defaultSchema, findReferenceCandidates, findInitialMatches, type DatasetSchema, type ResponseFormat, type PseudonymizedDataset } from './lib/core';
import { loadFile, loadClipboardText, type DelimitedFormat } from './lib/input/loadDataset';
import { SessionVault } from './domain/shred/sessionVault';
import { resolveText } from './domain/result/resolve';
import { ReferenceEditor, type CellReference } from './components/ReferenceEditor';

const vault = new SessionVault<PseudonymizedDataset>();
type RawRecord = Record<string, any>;

export default function App() {
  const [rawRecords, setRawRecords] = useState<RawRecord[]>([]); const [dataset, setDataset] = useState<PseudonymizedDataset | null>(null); const [schema, setSchema] = useState<DatasetSchema | null>(null); const [aliases, setAliases] = useState<Record<string, string>>({}); const [cellReferences, setCellReferences] = useState<CellReference[]>([]); const [task, setTask] = useState('Make an order based on food preferences.'); const [format, setFormat] = useState<ResponseFormat>('tsv'); const [aiResult, setAiResult] = useState(''); const [resolved, setResolved] = useState(''); const [error, setError] = useState(''); const [restored, setRestored] = useState(false); const [copied, setCopied] = useState<'prompt' | 'data' | 'result' | null>(null); const [loading, setLoading] = useState(false); const [promptDraft, setPromptDraft] = useState(''); const [pasteText, setPasteText] = useState(''); const [pasteFormat, setPasteFormat] = useState<DelimitedFormat>('tsv'); const [loadedFrom, setLoadedFrom] = useState(''); const fileInput = useRef<HTMLInputElement>(null);
  useEffect(() => { vault.restore().then(data => { if (data) { setDataset(data); setSchema(data.schema ?? null); setRestored(true); } }).catch(() => undefined); }, []);
  function updateSchema(fn: (s: DatasetSchema) => DatasetSchema) { setSchema(s => s ? fn(structuredClone(s)) : s); }
  const promptResult = useMemo(() => {
    if (!dataset || !schema) return { rows: dataset?.rows ?? [], error: null as string | null, notes: [] as string[] };
    const notes: string[] = [];
    try {
      const rows = applySchema(Object.values(dataset.mapping), dataset.rows.map(r => r.pseudonym), schema, 'username', { aliases, cellReferences, notes });
      return { rows, error: null as string | null, notes };
    } catch (e) {
      return { rows: [], error: e instanceof Error ? e.message : 'Could not resolve references.', notes: [] as string[] };
    }
  }, [dataset, schema, aliases, cellReferences]);
  const promptRows = promptResult.rows;
  const referenceError = promptResult.error;
  const referenceNotes = promptResult.notes;
  const prompt = useMemo(() => dataset && vault.sessionId && !referenceError ? buildPrompt(promptRows, promptDraft || task, format, vault.sessionId, schema ?? undefined) : '', [dataset, promptRows, promptDraft, task, format, schema, referenceError]);
  const referenceColumns = schema?.columns.filter(c => c.mode === 'reference' && c.referenceTarget) ?? [];
  const referenceCandidates = useMemo(() => { const out: Record<string, string[]> = {}; for (const column of referenceColumns) out[column.name] = [...new Set(rawRecords.map(r => String(r[column.name] ?? '')).filter(Boolean))]; return out; }, [rawRecords, referenceColumns]);
  async function copy(text: string, kind: 'prompt' | 'data' | 'result') { await navigator.clipboard.writeText(text); setCopied(kind); window.setTimeout(() => setCopied(c => c === kind ? null : c), 1800); }
  async function loadRecords(records: RawRecord[], source: string) { if (!records.length) throw new Error('No rows were found.'); setRawRecords(records); setLoadedFrom(source); setError(''); }
  async function onFile(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; try { setLoading(true); const kind = /\.xlsx?$/i.test(file.name) ? 'Excel file' : 'CSV file'; await loadRecords(await loadFile(file), kind); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load file.'); } finally { setLoading(false); } }
  async function onClipboard() { try { setLoading(true); const text = await navigator.clipboard.readText(); await loadRecords(await loadClipboardText(text, pasteFormat), `OS clipboard (${pasteFormat.toUpperCase()})`); } catch (e) { setError(e instanceof Error ? e.message : 'Could not read clipboard.'); } finally { setLoading(false); } }
  async function onPasteChange(text: string, formatOverride?: DelimitedFormat) { setPasteText(text); const activeFormat = formatOverride ?? pasteFormat; try { const records = await loadClipboardText(text, activeFormat); if (records.length) await loadRecords(records, `Pasted text (${activeFormat.toUpperCase()})`); else if (!text.trim()) setRawRecords([]); } catch { /* ignore invalid input while typing */ } }
  async function handlePseudonymize() { try { setError(''); setResolved(''); if (!rawRecords.length) throw new Error('Load a dataset first.'); const base = pseudonymize(rawRecords); const nextSchema = defaultSchema(rawRecords); const rows = applySchema(rawRecords, base.rows.map(r => r.pseudonym), nextSchema); const result = { ...base, rows, schema: nextSchema }; await vault.create(result); setDataset(result); setSchema(nextSchema); } catch (e) { setError(e instanceof Error ? e.message : 'Could not pseudonymize data.'); } }
  function changeMode(index: number, mode: any) { updateSchema(s => { s.columns[index].mode = mode; if (mode === 'reference' && !s.columns[index].referenceTarget) s.columns[index].referenceTarget = s.columns.find(c => c.mode === 'pseudonymize')?.name; if (mode !== 'reference') delete s.columns[index].referenceTarget; return s; }); }
  function mapAlias(reference: string, target: string) { setAliases(a => ({ ...a, [reference]: target })); }
  function addPromptText(text: string) { setPromptDraft(v => `${v}${v && !/[\s]$/.test(v) ? ' ' : ''}${text}`); }
  function addColumn(name: string) { addPromptText(`{{${name}}}`); }
  function addPseudonymizedValues() { addPromptText('{{pseudonymized values}}'); }
  async function handleResolve() { try { if (!dataset || !schema || !vault.sessionId) throw new Error('Create or restore a session first.'); const result = parseSessionResponse(aiResult, format, vault.sessionId); const validation = validateResults(result, dataset.rows.map(r => r.pseudonym)); if (validation.unknown.length || validation.duplicatePseudonyms.length || validation.missingPseudonyms.length) throw new Error(`Result rejected: ${validation.unknown.length} unknown, ${validation.duplicatePseudonyms.length} duplicate, ${validation.missingPseudonyms.length} missing pseudonym(s).`); const projected = projectOutput(result, schema.output); const identityColumn = schema.columns.find(c => c.mode === 'pseudonymize')?.name ?? 'username'; const mappings = Object.entries(dataset.mapping).map(([pseudonym, record]) => ({ pseudonym, identity: String(record[identityColumn] ?? pseudonym) })); setError(''); setResolved(resolveText(JSON.stringify(projected, null, 2), mappings)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not validate AI result.'); setResolved(''); } }
  async function handleShred() { await vault.shred(); setDataset(null); setSchema(null); setRawRecords([]); setAliases({}); setCellReferences([]); setAiResult(''); setResolved(''); setRestored(false); setCopied(null); setError('Session shredded.'); setPromptDraft(''); setPasteText(''); setLoadedFrom(''); setFormat('tsv'); }
  return <Container maxWidth="lg" sx={{ py: 4 }}><Stack spacing={3}>
    <Box><Typography variant="h3">🎭 de-pseudo</Typography><Typography color="text.secondary">Pseudonymize before AI. Resolve locally. Shred when finished.</Typography></Box>
    <Paper variant="outlined" sx={{ p: 3, background: 'linear-gradient(135deg, rgba(193,84,12,0.07), rgba(192,138,46,0.07))' }}><Stack spacing={2}>
      <Typography variant="h6">How it works</Typography>
      <Stack direction="row" spacing={1} flexWrap="wrap" alignItems="center" useFlexGap>
        <Chip label="📋 Your data" /><Typography color="text.secondary">→</Typography>
        <Chip label="🎭 Pseudonymize" /><Typography color="text.secondary">→</Typography>
        <Chip label="✏️ Build prompt" /><Typography color="text.secondary">→</Typography>
        <Chip label="🤖 AI sees only tokens" /><Typography color="text.secondary">→</Typography>
        <Chip label="🔓 Resolve locally" /><Typography color="text.secondary">→</Typography>
        <Chip label="🗑️ Shred" />
      </Stack>
      <Typography variant="body2" color="text.secondary">Names and other identifiers are swapped for random tokens before anything is copied out to an AI. The AI only ever sees those tokens plus whatever data you explicitly allow through; only this browser tab holds the mapping back to real identities, and only until you shred it.</Typography>
      <Alert severity="info" icon={false}>🔍 <b>Note:</b> this provides <b>pseudonymization</b> — and, depending on what other data travels alongside it, potentially <b>anonymization</b> — of what you send to an AI system. Pseudonymization alone does not guarantee anonymity: free text, rare attribute combinations, or surrounding context can still make someone identifiable even without their name. Review what you send before it leaves this tab.</Alert>
    </Stack></Paper>
    {restored && <Alert severity="info">Encrypted local session restored. Identity mapping remains local.</Alert>}{error && <Alert severity={error === 'Session shredded.' ? 'success' : 'error'}>{error}</Alert>}
    {!dataset && <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">1. Load data</Typography><Typography variant="body2" color="text.secondary">Everything is processed locally in the browser.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><input ref={fileInput} type="file" hidden accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" onChange={onFile} /><Button variant="contained" onClick={() => fileInput.current?.click()} disabled={loading}>Load file (CSV, Excel) +</Button><Button variant="outlined" onClick={onClipboard} disabled={loading}>Load clipboard</Button></Stack><Stack direction="row" spacing={1} alignItems="center"><Typography variant="body2" color="text.secondary">Paste format:</Typography><ToggleButtonGroup size="small" exclusive value={pasteFormat} onChange={(_, v: DelimitedFormat | null) => { if (v) { setPasteFormat(v); onPasteChange(pasteText, v); } }}><ToggleButton value="tsv">TSV (tab)</ToggleButton><ToggleButton value="csv">CSV (comma)</ToggleButton></ToggleButtonGroup></Stack><TextField label="Paste data" multiline minRows={3} value={pasteText} onChange={e => onPasteChange(e.target.value)} placeholder={pasteFormat === 'csv' ? 'username,preference\nAlice,pizza' : 'username\tpreference\nAlice\tpizza'} fullWidth />{rawRecords.length > 0 && <><Typography variant="body2">Loaded {rawRecords.length} rows from {loadedFrom}.</Typography><TableContainer sx={{ maxHeight: 360 }}><Table stickyHeader size="small"><TableHead><TableRow>{Object.keys(rawRecords[0]).map(c => <TableCell key={c}>{c}</TableCell>)}</TableRow></TableHead><TableBody>{rawRecords.map((row, ri) => <TableRow key={ri}>{Object.keys(rawRecords[0]).map(c => <TableCell key={c}>{String(row[c] ?? '')}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer><Button variant="contained" onClick={handlePseudonymize}>Pseudonymize & save locally</Button></>}</Stack></Paper>}
    {dataset && schema && <>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">1. Dataset editor</Typography><Typography variant="body2" color="text.secondary">Reference columns have a ↗ handle. Drag it directly to a pseudonymized person cell.</Typography><ReferenceEditor rows={rawRecords} columns={schema.columns.map(c => c.name)} referenceColumns={referenceColumns.map(c => c.name)} pseudonymizedColumns={schema.columns.filter(c => c.mode === 'pseudonymize').map(c => c.name)} references={cellReferences} onChange={setCellReferences} /></Stack></Paper>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">2. Privacy & columns</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>Column</TableCell><TableCell>Privacy mode</TableCell><TableCell>Reference target</TableCell></TableRow></TableHead><TableBody>{schema.columns.map((column, i) => <TableRow key={column.name}><TableCell>{column.name}</TableCell><TableCell><FormControl size="small" fullWidth><InputLabel>Mode</InputLabel><Select label="Mode" value={column.mode} onChange={e => changeMode(i, e.target.value)}><MenuItem value="keep">Keep</MenuItem><MenuItem value="pseudonymize">Pseudonymize</MenuItem><MenuItem value="reference">Reference</MenuItem><MenuItem value="remove">Remove</MenuItem></Select></FormControl></TableCell><TableCell>{column.mode === 'reference' ? <FormControl size="small" fullWidth><InputLabel>Target</InputLabel><Select label="Target" value={column.referenceTarget ?? ''} onChange={e => updateSchema(s => { s.columns[i].referenceTarget = e.target.value; return s; })}>{schema.columns.filter(c => c.mode === 'pseudonymize').map(c => <MenuItem key={c.name} value={c.name}>{c.name}</MenuItem>)}</Select></FormControl> : '—'}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Stack></Paper>
      {referenceColumns.length > 0 && <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">4. Resolve text references</Typography>{referenceError && <Alert severity="warning">{referenceError}</Alert>}{referenceNotes.length > 0 && <Alert severity="info">{referenceNotes.map(note => <Box key={note}>{note}</Box>)}</Alert>}{referenceColumns.map(column => <Box key={column.name}><Typography fontWeight="bold">{column.name} → {column.referenceTarget}</Typography>{(referenceCandidates[column.name] ?? []).map(reference => { const targetValues = rawRecords.map(r => String(r[column.referenceTarget!] ?? '')).filter(Boolean); const candidates = findReferenceCandidates(targetValues, reference); const ambiguous = candidates.length > 1; const initialMatches = candidates.length === 0 ? findInitialMatches([...new Set(targetValues)], reference) : []; const inferred = initialMatches.length === 1 ? initialMatches[0] : null; const others = [...new Set(targetValues)].filter(v => !candidates.includes(v)); const options = [...candidates, ...others]; const aliasKey = `${column.name}:${reference}`; return <Box key={reference} sx={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 1, alignItems: 'center', my: 1 }}><Typography>{reference}{ambiguous && <Typography component="span" variant="body2" color="warning.main"> (matches {candidates.length} people)</Typography>}{candidates.length === 0 && !inferred && <Typography component="span" variant="body2" color="text.secondary"> (no automatic match — choose the person)</Typography>}{inferred && <Typography component="span" variant="body2" color="info.main"> (partial match resolved to "{inferred}" — verify)</Typography>}</Typography><FormControl size="small"><InputLabel>Person</InputLabel><Select label="Person" value={aliases[aliasKey] ?? inferred ?? ''} onChange={e => mapAlias(aliasKey, e.target.value)}><MenuItem value=""><em>Unresolved</em></MenuItem>{options.map(c => <MenuItem key={c} value={c}>{c}</MenuItem>)}</Select></FormControl></Box>; })}</Box>)}</Stack></Paper>}
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">5. Prompt constructor</Typography><Typography variant="body2" color="text.secondary">Click a column to insert its placeholder into the prompt. Add pseudonymized values when the AI should reason over the protected dataset.</Typography><Stack direction="row" spacing={1} flexWrap="wrap">{schema.columns.filter(c => c.mode !== 'remove').map(c => <Button key={c.name} size="small" variant="outlined" onClick={() => addColumn(c.name)}>{c.name}</Button>)}<Button size="small" variant="contained" onClick={addPseudonymizedValues}>Add pseudonymized values</Button></Stack><TextField label="Prompt" multiline minRows={8} value={promptDraft} onChange={e => setPromptDraft(e.target.value)} placeholder="Describe the task, then insert columns or pseudonymized values..." fullWidth /></Stack></Paper>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">6. AI output</Typography>{schema.columns.filter(c => c.mode !== 'remove').map(column => <FormControlLabel key={column.name} control={<Checkbox checked={schema.output.some(o => o.name === column.name)} onChange={e => updateSchema(s => { const exists = s.output.some(o => o.name === column.name); s.output = e.target.checked && !exists ? [...s.output, { name: column.name, source: column.name === 'username' ? 'pseudonym' : column.name }] : !e.target.checked ? s.output.filter(o => o.name !== column.name) : s.output; return s; })} />} label={column.name} />)}<TextField label="AI-generated output field name" placeholder="selected_food" onKeyDown={e => { if (e.key === 'Enter') { const name = (e.target as HTMLInputElement).value.trim(); if (name) { updateSchema(s => { if (!s.output.some(o => o.name === name)) s.output.push({ name }); return s; }); (e.target as HTMLInputElement).value = ''; } } }} helperText="Press Enter to add a new AI-generated field" /></Stack></Paper>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">7. Generated AI prompt</Typography><Stack direction="row" spacing={1} alignItems="center"><Typography variant="body2" color="text.secondary">AI reply format:</Typography><ToggleButtonGroup size="small" exclusive value={format} onChange={(_, v: ResponseFormat | null) => v && setFormat(v)}><ToggleButton value="tsv">TSV</ToggleButton><ToggleButton value="csv">CSV</ToggleButton><ToggleButton value="json">JSON</ToggleButton></ToggleButtonGroup></Stack>{referenceError ? <Alert severity="error">Prompt generation is blocked until the unresolved references above are fixed.</Alert> : <><TextField multiline minRows={8} value={prompt} InputProps={{ readOnly: true }} fullWidth /><Button variant="outlined" onClick={() => copy(prompt, 'prompt')}>{copied === 'prompt' ? 'Copied' : 'Copy prompt'}</Button></>}</Stack></Paper>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">8. Paste AI result</Typography><TextField multiline minRows={7} value={aiResult} onChange={e => setAiResult(e.target.value)} fullWidth /><Button variant="contained" onClick={handleResolve}>Validate & resolve locally</Button></Stack></Paper>
      {resolved && <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">9. Final output</Typography><TextField multiline minRows={5} value={resolved} InputProps={{ readOnly: true }} fullWidth /><Button variant="contained" onClick={() => copy(resolved, 'result')}>{copied === 'result' ? 'Copied' : 'Copy'}</Button></Stack></Paper>}
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">10. Cryptoshred</Typography><Button color="error" variant="contained" onClick={handleShred}>Shred session</Button></Stack></Paper>
    </>}
    <Box component="footer" sx={{ pt: 2, borderTop: '1px solid', borderColor: 'divider', display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: 1 }}>
      <Typography variant="body2" color="text.secondary">Developed by <Link href="https://github.com/jsilvanus" target="_blank" rel="noopener noreferrer">Juha Itäleino (@jsilvanus)</Link> · <Link href="https://github.com/jsilvanus/de-pseudo" target="_blank" rel="noopener noreferrer">source on GitHub</Link></Typography>
      <Typography variant="body2" color="text.secondary">Licensed under the <Link href="https://github.com/jsilvanus/de-pseudo/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">EUPL-1.2</Link></Typography>
    </Box>
  </Stack></Container>;
}
