import { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, Box, Button, Checkbox, Container, FormControl, FormControlLabel, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { pseudonymize, applySchema, buildPrompt, parseSessionResponse, validateResults, projectOutput, defaultSchema, findReferenceCandidates, type DatasetSchema, type ResponseFormat, type PseudonymizedDataset } from './lib/core';
import { loadFile, loadClipboardText } from './lib/input/loadDataset';
import { SessionVault } from './domain/shred/sessionVault';
import { resolveResult } from './domain/result/resolveResult';
import { ReferenceEditor, type CellReference } from './components/ReferenceEditor';

const vault = new SessionVault<PseudonymizedDataset>();
type RawRecord = Record<string, any>;

export default function App() {
  const [rawRecords, setRawRecords] = useState<RawRecord[]>([]); const [dataset, setDataset] = useState<PseudonymizedDataset | null>(null); const [schema, setSchema] = useState<DatasetSchema | null>(null);
  const [aliases, setAliases] = useState<Record<string, string>>({}); const [cellReferences, setCellReferences] = useState<CellReference[]>([]); const [task, setTask] = useState('Make an order based on food preferences.'); const [format, setFormat] = useState<ResponseFormat>('lines'); const [aiResult, setAiResult] = useState(''); const [resolved, setResolved] = useState(''); const [error, setError] = useState(''); const [restored, setRestored] = useState(false); const [copied, setCopied] = useState<'prompt' | 'data' | 'result' | null>(null); const [loading, setLoading] = useState(false); const fileInput = useRef<HTMLInputElement>(null);
  useEffect(() => { vault.restore().then(data => { if (data) { setDataset(data); setSchema(data.schema ?? null); setRestored(true); } }).catch(() => undefined); }, []);
  function updateSchema(fn: (s: DatasetSchema) => DatasetSchema) { setSchema(s => s ? fn(structuredClone(s)) : s); }
  const promptRows = useMemo(() => dataset && schema ? applySchema(Object.values(dataset.mapping), dataset.rows.map(r => r.pseudonym), schema) : dataset?.rows ?? [], [dataset, schema]);
  const prompt = useMemo(() => dataset && vault.sessionId ? buildPrompt(promptRows, task, format, vault.sessionId, schema ?? undefined) : '', [dataset, promptRows, task, format, schema]);
  const referenceColumns = schema?.columns.filter(c => c.mode === 'reference' && c.referenceTarget) ?? [];
  const referenceCandidates = useMemo(() => { const out: Record<string, string[]> = {}; for (const column of referenceColumns) out[column.name] = [...new Set(rawRecords.map(r => String(r[column.name] ?? '')).filter(Boolean))]; return out; }, [rawRecords, referenceColumns]);
  async function copy(text: string, kind: 'prompt' | 'data' | 'result') { await navigator.clipboard.writeText(text); setCopied(kind); window.setTimeout(() => setCopied(c => c === kind ? null : c), 1800); }
  async function loadRecords(records: RawRecord[]) { if (!records.length) throw new Error('No rows were found.'); setRawRecords(records); setError(''); }
  async function onFile(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; try { setLoading(true); await loadRecords(await loadFile(file)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load file.'); } finally { setLoading(false); } }
  async function onClipboard() { try { setLoading(true); const text = await navigator.clipboard.readText(); await loadRecords(await loadClipboardText(text)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not read clipboard.'); } finally { setLoading(false); } }
  async function handlePseudonymize() { try { setError(''); setResolved(''); if (!rawRecords.length) throw new Error('Load a dataset first.'); const base = pseudonymize(rawRecords); const nextSchema = defaultSchema(rawRecords); const rows = applySchema(rawRecords, base.rows.map(r => r.pseudonym), nextSchema); const result = { ...base, rows, schema: nextSchema }; await vault.create(result); setDataset(result); setSchema(nextSchema); } catch (e) { setError(e instanceof Error ? e.message : 'Could not pseudonymize data.'); } }
  function changeMode(index: number, mode: any) { updateSchema(s => { s.columns[index].mode = mode; if (mode === 'reference' && !s.columns[index].referenceTarget) s.columns[index].referenceTarget = s.columns.find(c => c.mode === 'pseudonymize')?.name; if (mode !== 'reference') delete s.columns[index].referenceTarget; return s; }); }
  function mapAlias(reference: string, target: string) { setAliases(a => ({ ...a, [reference]: target })); }
  async function handleResolve() { try { if (!dataset || !schema || !vault.sessionId) throw new Error('Create or restore a session first.'); const result = parseSessionResponse(aiResult, format, vault.sessionId); const validation = validateResults(result, dataset.rows.map(r => r.pseudonym)); if (validation.unknown.length || validation.duplicatePseudonyms.length || validation.missingPseudonyms.length) throw new Error(`Result rejected: ${validation.unknown.length} unknown, ${validation.duplicatePseudonyms.length} duplicate, ${validation.missingPseudonyms.length} missing pseudonym(s).`); const projected = projectOutput(result, schema.output); setError(''); setResolved(JSON.stringify(resolveResult(JSON.stringify(projected), dataset.mapping), null, 2)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not validate AI result.'); setResolved(''); } }
  async function handleShred() { await vault.shred(); setDataset(null); setSchema(null); setRawRecords([]); setAliases({}); setCellReferences([]); setAiResult(''); setResolved(''); setRestored(false); setCopied(null); setError('Session shredded.'); }
  return <Container maxWidth="lg" sx={{ py: 4 }}><Stack spacing={3}>
    <Box><Typography variant="h3">de-pseudo</Typography><Typography color="text.secondary">Pseudonymize before AI. Resolve locally. Shred when finished.</Typography></Box>
    {restored && <Alert severity="info">Encrypted local session restored. Identity mapping remains local.</Alert>}{error && <Alert severity={error === 'Session shredded.' ? 'success' : 'error'}>{error}</Alert>}
    {!dataset && <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">1. Load data</Typography><Typography variant="body2" color="text.secondary">Everything is processed locally in the browser.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><input ref={fileInput} type="file" hidden accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" onChange={onFile} /><Button variant="contained" onClick={() => fileInput.current?.click()} disabled={loading}>Load file (CSV, Excel) +</Button><Button variant="outlined" onClick={onClipboard} disabled={loading}>Load clipboard</Button></Stack>{rawRecords.length > 0 && <><Typography variant="body2">Loaded {rawRecords.length} rows.</Typography><TableContainer sx={{ maxHeight: 360 }}><Table stickyHeader size="small"><TableHead><TableRow>{Object.keys(rawRecords[0]).map(c => <TableCell key={c}>{c}</TableCell>)}</TableRow></TableHead><TableBody>{rawRecords.map((row, ri) => <TableRow key={ri}>{Object.keys(rawRecords[0]).map(c => <TableCell key={c}>{String(row[c] ?? '')}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer><Button variant="contained" onClick={handlePseudonymize}>Pseudonymize & save locally</Button></>}</Stack></Paper>}
    {dataset && schema && <>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">1. Dataset editor</Typography><TableContainer sx={{ maxHeight: 420 }}><Table stickyHeader size="small"><TableHead><TableRow>{schema.columns.map(c => <TableCell key={c.name}>{c.name}</TableCell>)}</TableRow></TableHead><TableBody>{rawRecords.map((row, ri) => <TableRow key={ri}>{schema.columns.map(c => <TableCell key={c.name}>{String(row[c.name] ?? '')}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer></Stack></Paper>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">2. Privacy & columns</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>Column</TableCell><TableCell>Privacy mode</TableCell><TableCell>Reference target</TableCell></TableRow></TableHead><TableBody>{schema.columns.map((column, i) => <TableRow key={column.name}><TableCell>{column.name}</TableCell><TableCell><FormControl size="small" fullWidth><InputLabel>Mode</InputLabel><Select label="Mode" value={column.mode} onChange={e => changeMode(i, e.target.value)}><MenuItem value="keep">Keep</MenuItem><MenuItem value="pseudonymize">Pseudonymize</MenuItem><MenuItem value="reference">Reference</MenuItem><MenuItem value="remove">Remove</MenuItem></Select></FormControl></TableCell><TableCell>{column.mode === 'reference' ? <FormControl size="small" fullWidth><InputLabel>Target</InputLabel><Select label="Target" value={column.referenceTarget ?? ''} onChange={e => updateSchema(s => { s.columns[i].referenceTarget = e.target.value; return s; })}>{schema.columns.filter(c => c.mode === 'pseudonymize').map(c => <MenuItem key={c.name} value={c.name}>{c.name}</MenuItem>)}</Select></FormControl> : '—'}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Stack></Paper>
      {referenceColumns.map(column => <ReferenceEditor key={column.name} rows={rawRecords} referenceColumn={column.name} targetColumn={column.referenceTarget!} references={cellReferences.filter(r => r.sourceColumn === column.name && r.targetColumn === column.referenceTarget)} onChange={refs => setCellReferences(current => [...current.filter(r => r.sourceColumn !== column.name), ...refs])} />)}
      {referenceColumns.length > 0 && <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">4. Resolve text references</Typography>{referenceColumns.map(column => <Box key={column.name}><Typography fontWeight="bold">{column.name} → {column.referenceTarget}</Typography>{(referenceCandidates[column.name] ?? []).map(reference => { const targetValues = rawRecords.map(r => String(r[column.referenceTarget!] ?? '')).filter(Boolean); const candidates = findReferenceCandidates(targetValues, reference); return <Box key={reference} sx={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 1, alignItems: 'center', my: 1 }}><Typography>{reference}</Typography><FormControl size="small"><InputLabel>Person</InputLabel><Select label="Person" value={aliases[`${column.name}:${reference}`] ?? ''} onChange={e => mapAlias(`${column.name}:${reference}`, e.target.value)}><MenuItem value=""><em>Unresolved</em></MenuItem>{[...new Set(candidates)].map(c => <MenuItem key={c} value={c}>{c}</MenuItem>)}</Select></FormControl></Box>; })}</Box>)}</Stack></Paper>}
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">5. AI output</Typography>{schema.columns.filter(c => c.mode !== 'remove').map(column => <FormControlLabel key={column.name} control={<Checkbox checked={schema.output.some(o => o.name === column.name)} onChange={e => updateSchema(s => { const exists = s.output.some(o => o.name === column.name); s.output = e.target.checked && !exists ? [...s.output, { name: column.name, source: column.name === 'username' ? 'pseudonym' : column.name }] : !e.target.checked ? s.output.filter(o => o.name !== column.name) : s.output; return s; })} />} label={column.name} />)}<TextField label="AI-generated output field name" placeholder="selected_food" onKeyDown={e => { if (e.key === 'Enter') { const name = (e.target as HTMLInputElement).value.trim(); if (name) { updateSchema(s => { if (!s.output.some(o => o.name === name)) s.output.push({ name }); return s; }); (e.target as HTMLInputElement).value = ''; } } }} helperText="Press Enter to add a new AI-generated field" /></Stack></Paper>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">6. Pseudonymized data</Typography><TextField multiline minRows={6} value={JSON.stringify(promptRows, null, 2)} InputProps={{ readOnly: true }} fullWidth /><Button variant="outlined" onClick={() => copy(JSON.stringify(promptRows, null, 2), 'data')}>{copied === 'data' ? 'Copied' : 'Copy pseudonymized data'}</Button></Stack></Paper>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">7. AI prompt</Typography><TextField label="Task" value={task} onChange={e => setTask(e.target.value)} fullWidth /><FormControl fullWidth><InputLabel>Response format</InputLabel><Select label="Response format" value={format} onChange={e => setFormat(e.target.value as ResponseFormat)}><MenuItem value="lines">Simple lines</MenuItem><MenuItem value="json">JSON</MenuItem></Select></FormControl><TextField multiline minRows={8} value={prompt} InputProps={{ readOnly: true }} fullWidth /><Button variant="outlined" onClick={() => copy(prompt, 'prompt')}>{copied === 'prompt' ? 'Copied' : 'Copy prompt'}</Button></Stack></Paper>
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">8. Paste AI result</Typography><TextField multiline minRows={7} value={aiResult} onChange={e => setAiResult(e.target.value)} fullWidth /><Button variant="contained" onClick={handleResolve}>Validate & resolve locally</Button></Stack></Paper>
      {resolved && <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">9. Final output</Typography><TextField multiline minRows={5} value={resolved} InputProps={{ readOnly: true }} fullWidth /><Button variant="contained" onClick={() => copy(resolved, 'result')}>{copied === 'result' ? 'Copied' : 'Copy'}</Button></Stack></Paper>}
      <Paper sx={{ p: 3 }}><Stack spacing={2}><Typography variant="h5">10. Cryptoshred</Typography><Button color="error" variant="contained" onClick={handleShred}>Shred session</Button></Stack></Paper>
    </>}
  </Stack></Container>;
}
